/*
 * Kernel API compatibility switches for natflow.
 *
 * Keep version checks here whenever possible.  Call sites should use the
 * feature/API name, not the kernel version that introduced it.
 */
#ifndef _NATFLOW_COMPAT_H_
#define _NATFLOW_COMPAT_H_

#include <linux/version.h>

#define NATFLOW_KERNEL_BEFORE(major, minor, patch) \
	(LINUX_VERSION_CODE < KERNEL_VERSION(major, minor, patch))
#define NATFLOW_KERNEL_AT_LEAST(major, minor, patch) \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(major, minor, patch))
#define NATFLOW_KERNEL_IN_RANGE(from_major, from_minor, from_patch, to_major, to_minor, to_patch) \
	(NATFLOW_KERNEL_AT_LEAST(from_major, from_minor, from_patch) && \
	 NATFLOW_KERNEL_BEFORE(to_major, to_minor, to_patch))

#define NATFLOW_NF_HOOK_OPS_HAVE_HOOKNUM_ARG NATFLOW_KERNEL_BEFORE(3, 13, 0)
#define NATFLOW_NF_HOOK_OPS_HAVE_DEV_ARGS \
	NATFLOW_KERNEL_IN_RANGE(3, 13, 0, 4, 1, 0)
#define NATFLOW_NF_HOOK_OPS_HAVE_STATE_ARG \
	NATFLOW_KERNEL_IN_RANGE(4, 1, 0, 4, 4, 0)
#define NATFLOW_NF_HOOK_STATE_HAS_OUTDEV NATFLOW_KERNEL_BEFORE(4, 10, 0)
#define NATFLOW_NF_HOOK_OPS_HAVE_OWNER NATFLOW_KERNEL_BEFORE(4, 4, 0)

#define NATFLOW_NF_CONNTRACK_FIND_GET_USES_ZONE_PTR NATFLOW_KERNEL_AT_LEAST(4, 3, 0)
#define NATFLOW_NF_CONNTRACK_TIMEOUT_IS_TIMER NATFLOW_KERNEL_BEFORE(4, 9, 0)
#define NATFLOW_NF_CONNTRACK_EXT_REPLACE_NEEDS_RCU NATFLOW_KERNEL_BEFORE(5, 5, 0)
#define NATFLOW_NF_CONNTRACK_EXT_ASSIGN_NEEDS_RCU NATFLOW_KERNEL_IN_RANGE(4, 9, 0, 5, 5, 0)
#define NATFLOW_NF_CONNTRACK_IN_TAKES_STATE NATFLOW_KERNEL_AT_LEAST(4, 20, 0)
#define NATFLOW_HAVE_NF_CONNTRACK_GLOBAL_HASH NATFLOW_KERNEL_AT_LEAST(4, 7, 0)
#define NATFLOW_HAVE_NF_CT_IS_EXPIRED NATFLOW_KERNEL_AT_LEAST(4, 9, 0)

#define NATFLOW_HAVE_NF_REGISTER_NET_HOOKS NATFLOW_KERNEL_AT_LEAST(4, 13, 0)
#define NATFLOW_HAVE_NF_RESET_CT NATFLOW_KERNEL_AT_LEAST(5, 4, 0)
#define NATFLOW_HAVE_NF_CT_EXPIRES NATFLOW_KERNEL_AT_LEAST(4, 7, 0)
#define NATFLOW_HAVE_NEW_CLASS_CREATE NATFLOW_KERNEL_AT_LEAST(6, 4, 0)
#define NATFLOW_HAVE_REGISTER_SYSCTL_PATH NATFLOW_KERNEL_AT_LEAST(6, 5, 0)
#define NATFLOW_HAVE_REGISTER_SYSCTL_SENTINEL NATFLOW_KERNEL_BEFORE(6, 5, 0)
#define NATFLOW_HAVE_OPENWRT_DSA_FLOW_OFFLOAD NATFLOW_KERNEL_AT_LEAST(5, 4, 0)
#define NATFLOW_DCCP_STATES_ARE_LOCAL NATFLOW_KERNEL_AT_LEAST(6, 17, 0)
#define NATFLOW_NF_CT_L4PROTO_FIND_TAKES_L4NUM NATFLOW_KERNEL_AT_LEAST(5, 1, 0)
#define NATFLOW_NF_CT_L4PROTO_FIND_TAKES_L4NUM_COMPAT \
	NATFLOW_KERNEL_IN_RANGE(4, 20, 0, 5, 1, 0)

#define NATFLOW_HAVE_IP_SET_STATE_API NATFLOW_KERNEL_AT_LEAST(4, 10, 0)
#define NATFLOW_HAVE_IP_SET_NET_API NATFLOW_KERNEL_AT_LEAST(3, 13, 0)
#define NATFLOW_HAVE_XT_ACTION_PARAM_NET NATFLOW_KERNEL_AT_LEAST(4, 4, 0)
#define NATFLOW_IP_SET_GET_BYNAME_TAKES_NLATTR \
	(NATFLOW_KERNEL_AT_LEAST(7, 0, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(6, 18, 22, 6, 19, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(6, 12, 81, 6, 13, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(6, 6, 134, 6, 7, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(6, 1, 167, 6, 2, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(5, 15, 203, 5, 16, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(5, 10, 253, 5, 11, 0))

#define NATFLOW_HAVE_SKB_TRY_MAKE_WRITABLE \
	(NATFLOW_KERNEL_AT_LEAST(4, 6, 0) || NATFLOW_KERNEL_IN_RANGE(4, 4, 15, 4, 5, 0))
#define NATFLOW_SKB_MAKE_WRITABLE_IS_ENSURE_WRITABLE NATFLOW_KERNEL_AT_LEAST(5, 3, 0)
#define NATFLOW_VLAN_HWACCEL_CLEAR_TAG_IS_EXPORTED NATFLOW_KERNEL_AT_LEAST(5, 0, 0)
#define NATFLOW_IP_SKB_DST_MTU_TAKES_NET NATFLOW_KERNEL_AT_LEAST(4, 7, 0)

#if NATFLOW_KERNEL_AT_LEAST(3, 7, 0) || \
    defined(CONFIG_NF_NAT_IPV6) || defined(CONFIG_NF_NAT_IPV6_MODULE)
#define NATFLOW_NAT66_AVAILABLE 1
#else
#define NATFLOW_NAT66_AVAILABLE 0
#endif
#define NATFLOW_NAT_RANGE_USES_IP_NAT_MANIP NATFLOW_KERNEL_BEFORE(3, 3, 0)
#define NATFLOW_NAT_RANGE_USES_IPV4_RANGE \
	NATFLOW_KERNEL_IN_RANGE(3, 3, 0, 3, 7, 0)
#define NATFLOW_NAT_RANGE_USES_RANGE2 NATFLOW_KERNEL_AT_LEAST(4, 18, 0)

#define NATFLOW_REFCOUNT_USES_REFCOUNT_T \
	(NATFLOW_KERNEL_IN_RANGE(5, 10, 236, 5, 11, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(5, 15, 36, 5, 16, 0) || \
	 NATFLOW_KERNEL_AT_LEAST(5, 17, 0))
#define NATFLOW_U64_STATS_HAS_ADD NATFLOW_KERNEL_AT_LEAST(6, 0, 0)
#define NATFLOW_HAVE_GET_RANDOM_U32 NATFLOW_KERNEL_AT_LEAST(4, 11, 0)
#define NATFLOW_NF_BRIDGE_PHYSINDEV_TAKES_NET \
	(NATFLOW_KERNEL_IN_RANGE(6, 1, 75, 6, 2, 0) || \
	 NATFLOW_KERNEL_IN_RANGE(6, 6, 14, 6, 7, 0) || \
	 NATFLOW_KERNEL_AT_LEAST(6, 7, 2))

#endif /* _NATFLOW_COMPAT_H_ */
